#ifndef _EXTI_H
#define _EXTI_H

#include <stdint.h>

struct EXTI {
	volatile uint32_t RTSR1, FTSR1, SWIER1, D3PMR1, D3PCR1L, D3PCR1H, RSVD0[2], RTSR2, FTSR2, SWIER2, D3PMR2,
	D3PCR2L, D3PCR2H, RTSR3, FTSR3, SWIER3, D3PMR3, D3PCR3L, D3PCR3H, RSVD1[10],
	CPUIMR1, CPUCPUEMR1, CPUPR1, RSVD2, CPUIMR2, CPUEMR2, CPUPR2, RSVD3, CPUIMR3, CPUEMR3, CPUPR3;
};

// define EXTI
#define EXTI ((struct EXTI*)0x58000000)

// IMPORTANT. EXTI REGISTERS ARE 32 bit READ/WRITE ACCESS ONLY.

#define EDGETYPE_RISING 0U
#define EDGETYPE_FALLING 1U
#define EDGETYPE_BOTH 2U

// used to configure interrupts.
void cfg_interrupt(uint8_t line, uint8_t edgetype);

#endif